apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dcgm-exporter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://nvidia.github.io/dcgm-exporter/helm-charts
    chart: dcgm-exporter
    targetRevision: 4.7.1
    helm:
      releaseName: dcgm-exporter
      values: |
        serviceMonitor:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: gpu-metrics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
