apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: modelops-api-cpu
spec:
  scaleTargetRef:
    name: modelops-api
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "60"
