apiVersion: v1
kind: Service
metadata:
  name: gpu-scheduler-service
  namespace: mlops-system
spec:
  selector:
    app: gpu-scheduler-service
  ports:
    - name: http
      port: 80
      targetPort: 8000
