apiVersion: v1
kind: Service
metadata:
  name: gpu-jobs-service
  namespace: mlops-system
spec:
  selector:
    app: gpu-jobs-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
