apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-saas
  namespace: argocd
spec:
  project: default
  source:
    repoURL: <REPO_URL>
    targetRevision: <REVISION>
    path: deploy/k8s/mlops-saas
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
