apiVersion: v1
kind: Service
metadata:
  name: control-plane-api-nodeport
spec:
  type: NodePort
  selector:
    app: control-plane-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080
